### PR TITLE
[office-addin-debugging] add option to skip prompt for enabling edge loopback

### PR DESCRIPTION
**Pull request by zhngx**

### CODE REVIEW

**Review by akrantz — CHANGES_REQUESTED** [review]
I don't think we really need to make this change. The problem on the servers is that the appcontainer for the edge webview is not registered properly.

**Comment by TCourtneyOwen** [comment]
@zhngx did you verify that this change in fact addresses the problem on VMs?

**Comment by akrantz** [comment]
It just skips the prompt, but it doesn't address the problem. If the Edge webview cannot access localhost, the add-in won't run.

**Comment by TCourtneyOwen** [comment]
Right, that's exactly what I was thinking, so I am not sure of the real value of this change

**Comment by zhngx** [comment]
It seem to work ok if I just skip the prompt and run through the tests. But sure it will be better to address the root issue instead of this temporary fix. I can always downgrade the package version to make sure our automation are running fine before we fix the root cause.

**Pull request closed without merging**
