### PR TITLE
[minor] Additional exclude custom function metadata filters

### PR DESCRIPTION
**Pull request by jeaniehuynh**
**Change Description**:

    Add a couple more mutually exclusive tags for @linkedEntityDataProvider custom functions.

### CODE REVIEW

**Review by akrantz — DISMISSED** [review]
Looks good.

**Comment by millerds** [comment]
Why the changes to the package-lock.json files?  They seem to be removing things (references to other office-addin-script packages) that shouldn't be.

**Comment by jeaniehuynh** [comment]
> Why the changes to the package-lock.json files? They seem to be removing things (references to other office-addin-script packages) that shouldn't be.

Those were just the changes that autogenerated when I ran the build. That said, I did initially run a build from the root directory first (not just from the custom-functions-metadata package) if that may have caused it? I can revert and rebuild to double check.

**Comment by akrantz** [comment]
When I looked at the package lock files, it pulled in the minor dependent package changes which happen. It's not the build but "npm install" at the root and the associated "lerna bootstrap" that is triggered which updates these. It's also fine to not add them.

**Review by akrantz — APPROVED** [review]

**Pull request merged**
