### PR TITLE
Update npm package-lock.json files

### PR DESCRIPTION
**Pull request by akrantz**
NOTE: This is using NPM v7 (7.5.2).

### CODE REVIEW

**Review by TCourtneyOwen — APPROVED** [review]

**Comment by akrantz** [comment]
@TCourtneyOwen On Monday, let's see see about updating the linux agent to Ubuntu 18 with the latest Node/NPM. The Linux agent is failing to build. I cannot tell why, but I just was able to do it using Ubuntu 18 (wsl).

**Comment by TCourtneyOwen** [comment]
Rerunning CI job

**Comment by TCourtneyOwen** [comment]
The build phase is failing for this PR:  https://office.visualstudio.com/OC/_build/results?buildId=7332478&view=logs&jobId=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&j=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&t=b638cbb7-b689-5675-daeb-41c1e3b6bd0e

**Comment by akrantz** [comment]
@TCourtneyOwen I've pushed changes which build locally.

**Comment by akrantz** [comment]
@TCourtneyOwen Everything passsed. Just need approval.

**Review by TCourtneyOwen — APPROVED** [review]

**Pull request merged**
