### PR TITLE
[office-addin-mainfest] update exports in main.ts

### LINKED ISSUE #253: [office-addin-manifest] Please export validate and xml
[main.ts](https://github.com/OfficeDev/Office-Addin-Scripts/blob/fdc18bba66e9688774fd33c14d2e997e9421e903/packages/office-addin-manifest/src/main.ts) contains exports of classes and functions that can then be imported like so:

```typescript
import { readManifestFile, ManifestInfo } from 'office-addin-manifest';
```

Please add `validate` and `xml` to this list, so that TypeScript can use the goodness in there as well:

```typescript
import { validateManifest, ManifestValidation } from 'office-addin-manifest';
```

Thank you.

### PR DESCRIPTION
**Pull request by TheSamsterZA**
Resolves #253.

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
Built changes and ran tests locally

**Comment by TheSamsterZA** [comment]
Thanks all! 😄

**Comment by TCourtneyOwen** [comment]
I will try and publish a new version of the package today

**Comment by TCourtneyOwen** [comment]
new package has been published as v.1.4.17

**Pull request merged**
