### PR TITLE
Use yaml files for Azure DevOps pipeline 

### PR DESCRIPTION
**Pull request by akrantz**
This will allow for making changes to the build pipeline using pull requests instead of directly editing the settings.

The Linux agent is specified as "ubuntu-latest" rather than "ubuntu-16.04". The latest is currently "ubuntu-18.04".

### CODE REVIEW

**Comment by akrantz** [comment]
@TCourtneyOwen "OfficeDev.Office-Addin-Scripts (1)" is the pipeline using yaml files. "Office-Addin-Scripts" is the old pipeline. Both have passed. Once this is merged, I can make the changes to switch to the yaml-based pipeline. The advantage of this is that we can use pull requests to make pipeline changes.

**Comment by TCourtneyOwen** [comment]
Why did you elect to have separate .yaml files for each step?

**Comment by akrantz** [comment]
It allows reusing the steps in other pipeline defintions, and organizes the code better so the main pipeline is more simple.

**Comment by TCourtneyOwen** [comment]
So once this is merged we should remove the pipeline already defined for Office-Addin-Scripts to remove redundancy such as the following> https://github.com/OfficeDev/Office-Addin-Scripts/pull/384

**Comment by akrantz** [comment]
Yes, I will fix it up so it just uses the yaml pipeline.

**Review by TCourtneyOwen — APPROVED** [review]

**Pull request merged**
