### PR TITLE
[Patch] Fix getInstalledApps.ps1 so it can get correct installed apps

### PR DESCRIPTION
**Pull request by pkkj**
**Change Description**:

   getInstalledApps.ps1 should look up the installed apps from 32-bit and 64-bit registry path.

1. **Do these changes impact *command syntax* of any of the packages?** (e.g., add/remove command, add/remove a command parameter, or update required parameters)
    No

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins)
    No

**Validation/testing performed**:

The script is validated with its consumer, isAzureCliInstalled() defined configure.ts

### CODE REVIEW

**Review by millerds — APPROVED** [review]

**Comment by millerds** [comment]
Thanks for the submission . . . looks like we need to update support of npm to v10.  This PR will have to go in after that (PR pending).

**Review by jargil — APPROVED** [review]

**Comment by millerds** [comment]
mac ci machine is having trouble and this fix doesn't apply to mac.

**Pull request merged**
