### PR TITLE
[patch] getHttpsServerOptions add params

### PR DESCRIPTION
**Pull request by KentonYu**
**Change Description**:
I want sign a cert for local ip, e.g. 127.1.1.1 \ 192.0.0.0, but getHttpsServerOptions can't pass the domains.

the function `getHttpsServerOptions` add three optional params, they are same as the function `ensureCertificatesAreInstalled` 's params.

1. **Do these changes impact *command syntax* of any of the packages?** (e.g., add/remove command, add/remove a command parameter, or update required parameters)
    If Yes, briefly describe what is impacted.

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins)
    If Yes, briefly describe what is impacted.

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

**Validation/testing performed**:

    Describe manual testing done.

### CODE REVIEW

**Comment by akrantz** [comment]
Seems OK to me.

**Comment by akrantz** [comment]
It might be helpful to make it a single param "options" with the object which contains the items, so you can do `getHttpServerOptions({domains: "abc"});`

**Review by millerds — APPROVED** [review]

**Comment by Nettsentrisk** [comment]
Great change, when will this be accessible through an npm release? :)

**Pull request merged**
