### PR TITLE
[patch] Remove sso .gitignore file

### PR DESCRIPTION
**Pull request by millerds**
Thank you for your pull request!  

Please add '[major]', '[minor]', or [patch] to the title to indicate the impact the change has on the code.  Please also provide the following information.

---

**Change Description**:
Remove the .gitignore file from office-addin-sso which is preventing the build output from being published.

1. **Do these changes impact *command syntax* of any of the packages?** (e.g., add/remove command, add/remove a command parameter, or update required parameters)
No.

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
No.

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

**Validation/testing performed**:
Ran tests.

### CODE REVIEW

**Comment by igor-ribeiiro** [comment]
Why is the building complaining about the `.gitignore` file?

**Comment by millerds** [comment]
> Why is the building complaining about the `.gitignore` file?

Building doesn't complain for office-addin-sso . . . that works fine.  However, because of the .gitignore npm publish doesn't publish the built lib folder in the tgz file.  And so with the add in project consumes it there isn't the js module files (form the lib folder) and so it fails to find the office-addin-sso module.

**Comment by igor-ribeiiro** [comment]
> > Why is the building complaining about the `.gitignore` file?
> 
> Building doesn't complain for office-addin-sso . . . that works fine. However, because of the .gitignore npm publish doesn't publish the built lib folder in the tgz file. And so with the add in project consumes it there isn't the js module files (form the lib folder) and so it fails to find the office-addin-sso module.

Can we just remove the lib folder line from the `.gitignore`? Then, it should stop ignoring the lib folder.

**Comment by millerds** [comment]
> > > Why is the building complaining about the `.gitignore` file?
> > 
> > 
> > Building doesn't complain for office-addin-sso . . . that works fine. However, because of the .gitignore npm publish doesn't publish the built lib folder in the tgz file. And so with the add in project consumes it there isn't the js module files (form the lib folder) and so it fails to find the office-addin-sso module.
> 
> Can we just remove the lib folder line from the `.gitignore`? Then, it should stop ignoring the lib folder.

I added the git ignore in order to change VS Code behavior that that is was broke things.  npm and VS Code ignore the node_modules folder be default so there is no need to have that as part of a .gitignore and all the other packages in this repo don't use a .gitignore (and now I know why).

**Review by igor-ribeiiro — APPROVED** [review]

**Pull request merged**
