### PR TITLE
Run npm install and ci on each package

### PR DESCRIPTION
**Pull request by millerds**
Individual package package-lock.json files seem to be out of sync with package.json.  This should bring them back into sync.

### CODE REVIEW

**Review by igor-ribeiiro — DISMISSED** [review]

**Comment by akrantz** [comment]
I usually would title a PR like this as "update package-lock.json files".

**Comment by akrantz** [comment]
@millerds I had no problems with npm install or running tests locally. I ran `npm audit fix` and pushed the commit to see what the updated packages do.

**Comment by akrantz** [comment]
There are errors about "filename too long" when checking out on the Windows machine.

**Comment by millerds** [comment]
> Usually this import would start with a lowercase letter...

The import is based on the name of the namespace I used.  I debated on using lower vs. upper case and saw that other objects imports were using upper (like ManifestInfo) so I used upper for the namespace.

**Comment by akrantz** [comment]
That's because ManifestInfo is a specific type, but since this is using * and is package, then convention is to have it be lowercase. The package name is also lowercase, but uses camelcase because you cannot have hyphens in the name.

**Comment by millerds** [comment]
> Do you really have to import this way for the sinon fakes to work?

Multiple places online indicated this problem with an updated version of typescript without any real solution.

The updated to typescript meant it wasn't generating code that would allow sinon to replace the method calls gotten by a "import * from ..." statement (done to me more inline with ES6).  By putting the methods in a namespace like this I can import using a "import {...} from ..." statement which get typescript to generate the coded needed.  I don't know of another workaround.

**Comment by millerds** [comment]
> That's because ManifestInfo is a specific type, but since this is using * and is package, then convention is to have it be lowercase. The package name is also lowercase, but uses camelcase because you cannot have hyphens in the name.

Can't use the import * when needing to use stubs (see other comment).

**Review by igor-ribeiiro — APPROVED** [review]

**Pull request merged**
