### PR TITLE
[office-addin-dev-settings] Update version of the commander dependency

### LINKED ISSUE #337: [office-addin-dev-settings] Update commander dependency
# Expected behavior

Using exported methods from office-addin-dev-settings should not cause compilation to fail.

# Current behavior

My app fails to compile.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Code snippet:

```typescript
// app.ts
import { sideloadAddIn } from 'office-addin-dev-settings';

async function foo(path) {
  await sideloadAddIn(path, undefined, true);
}
```

`tsc app.ts`

This will fail to compile due to commander. The bug was reported in multiple issues on the repo, and [a PR was merged in](https://github.com/tj/commander.js/pull/1146) and [released in the 5.0.0](https://github.com/tj/commander.js/releases/tag/v5.0.0).

## Context

I am building a CLI that wraps the great functionality provided by the packages that live here in this repo. Unfortunately, due to office-addin-dev-settings using an old version of the commander package, my NodeJS app fails to compile.

* Operating System: Windows 10 Version 20H2
* Node version: 15.1.0 with npm 6.14.8
* Office version: Microsoft Office 2016 Version 2012 (Build 13510.20004 Click-to-Run), Beta Channel
* Tool version: office-addin-dev-settings@1.8.8

## Failure Logs

```
node_modules/commander/typings/index.d.ts:26:25 - error TS2689: Cannot extend 
an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

26   class Command extends NodeJS.EventEmitter {
                           ~~~~~~

Found 1 error.
```

### PR DESCRIPTION
**Pull request by TheSamsterZA**
Resolves #337.

### CODE REVIEW

**Comment by TheSamsterZA** [comment]
I understand that commander is used across multiple office-addin packages, but was not sure if it was a good idea to update the dependency across all of them in one PR. I decided to limit my change to the package I was having trouble with.

**Comment by TCourtneyOwen** [comment]
@TheSamsterZA  Please resolve merge conflicts and submit a new iteration.

Thanks,

Courtney

**Comment by akrantz** [comment]
Thanks for bringing this to our attention. I think we should update this for all of the packages within office-addin-scripts.

**Review by akrantz — CHANGES_REQUESTED** [review]
Let's update this for all of the packages in office-addin-scripts.

**Comment by akrantz** [comment]
Also, is there a related update needed for @types/commander?

**Comment by akrantz** [comment]
It appears that @types/command is not actually needed. It would be nice to remove that.

**Comment by akrantz** [comment]
One other thing, with the major version update to commander, we'll need to ensure that there are no breaking changes which cause a problem. We don't have tests for the CLI itself. The release notes for the major version updates describe breaking changes: https://github.com/tj/commander.js/tags @TCourtneyOwen We can talk offline how best to validate this.

**Comment by TheSamsterZA** [comment]
@akrantz: 
> Let's update this for all of the packages in office-addin-scripts.

I've submitted a new pull request https://github.com/OfficeDev/Office-Addin-Scripts/pull/339 which does this. Please review.

**Comment by TheSamsterZA** [comment]
Closing since https://github.com/OfficeDev/Office-Addin-Scripts/pull/339 supersedes this PR.

**Pull request closed without merging**
