### PR TITLE
Office-Addin-Scripts: update commander dependency

### LINKED ISSUE #337: [office-addin-dev-settings] Update commander dependency
# Expected behavior

Using exported methods from office-addin-dev-settings should not cause compilation to fail.

# Current behavior

My app fails to compile.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Code snippet:

```typescript
// app.ts
import { sideloadAddIn } from 'office-addin-dev-settings';

async function foo(path) {
  await sideloadAddIn(path, undefined, true);
}
```

`tsc app.ts`

This will fail to compile due to commander. The bug was reported in multiple issues on the repo, and [a PR was merged in](https://github.com/tj/commander.js/pull/1146) and [released in the 5.0.0](https://github.com/tj/commander.js/releases/tag/v5.0.0).

## Context

I am building a CLI that wraps the great functionality provided by the packages that live here in this repo. Unfortunately, due to office-addin-dev-settings using an old version of the commander package, my NodeJS app fails to compile.

* Operating System: Windows 10 Version 20H2
* Node version: 15.1.0 with npm 6.14.8
* Office version: Microsoft Office 2016 Version 2012 (Build 13510.20004 Click-to-Run), Beta Channel
* Tool version: office-addin-dev-settings@1.8.8

## Failure Logs

```
node_modules/commander/typings/index.d.ts:26:25 - error TS2689: Cannot extend 
an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

26   class Command extends NodeJS.EventEmitter {
                           ~~~~~~

Found 1 error.
```

### PR DESCRIPTION
**Pull request by TheSamsterZA**
Resolves #337.

As requested by @akrantz in https://github.com/OfficeDev/Office-Addin-Scripts/pull/338#pullrequestreview-530234350.

Updates the following packages that have a direct dependency on commander:
custom-functions-metadata
office-addin-cli
office-addin-debugging
office-addin-dev-certs
office-addin-dev-settings
office-addin-lint
office-addin-manifest
office-addin-node-debugger
office-addin-sso
office-addin-test-server
office-addin-usage-data

### CODE REVIEW

**Comment by TheSamsterZA** [comment]
@TCourtneyOwen hello, do I need to do something special to get the Azure Pipelines build to run?

**Comment by akrantz** [comment]
@TheSamsterZA No, @TCourtneyOwen will look into it.

**Comment by akrantz** [comment]
@TheSamsterZA I wanted to also say thanks for making the updates. In the future, you can use the original pull request and just push additional commits to that branch. It's not neccessary to make a new pull request.

**Comment by TCourtneyOwen** [comment]
@TheSamsterZA I kicked off the run yesterday but it failed because of a problem with the VMs in the our CI Loop. I am fixing that this morning and will rerun the job.  I am sure it will pass then and I will merge your change.

Thanks,

Courtney

**Comment by akrantz** [comment]
I did some testing and I didn't seen any problems introduced from the latest version of commander.

**Comment by TCourtneyOwen** [comment]
CI job passed. I think we can go ahead and merge this now

**Review by akrantz — APPROVED** [review]

**Comment by TCourtneyOwen** [comment]
I have published new versions of the packages updated in this PR.

-Courtney

**Comment by TheSamsterZA** [comment]
Thanks all! 😄

**Pull request merged**
