### PR TITLE
[patch] Add custom function metadata auto-gen support for @linkedEntityLoadService

### PR DESCRIPTION
**Pull request by jeaniehuynh**
**Change Description**:

    Updating naming of @linkedEntityDataProvider to @linkedEntityLoadService

1. **Do these changes impact *command syntax* of any of the packages?** (e.g., add/remove command, add/remove a command parameter, or update required parameters)
    No

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins)
   No

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

### CODE REVIEW

**Comment by jeaniehuynh** [comment]
@millerds, could I get a review on this PR? Thank you!

**Comment by millerds** [comment]
Please remove unrelated changes to other packages (all the package-lock file change).

**Comment by millerds** [comment]
Why are we renaming it?  Does that break existing usages of the old name?

**Comment by jeaniehuynh** [comment]
> Why are we renaming it? Does that break existing usages of the old name?

We've re-arched this portion of our feature and the new name/signature aligns better with its new function. See this PR for more context: https://office.visualstudio.com/Office/_git/Office/pullrequest/3418078

This is part of a tented project, so only those customers are using this API currently and they are aware of this upcoming API change.

**Comment by jeaniehuynh** [comment]
> Please remove unrelated changes to other packages (all the package-lock file change).

@millerds done!

**Comment by akrantz** [comment]
The rename of the tag is fine. Personally, I preferred the data provider name from the service as this isn't really a service, but that's my own preference. But I know that this is being renamed due to the change in how the data provider function functions.

 There is an opportunity to have better type validation for the requires arguments to the function which uses the tag. Currently the tests just show `unknown` for the type. The previous version had the linkedProviderId as the first argument. The new form has a request. I think there should be a defined type for that argument type and this type should be required for the function. I would recommend this be done as part of a future change.

**Review by akrantz — APPROVED** [review]

**Comment by jeaniehuynh** [comment]
> The rename of the tag is fine. Personally, I preferred the data provider name from the service as this isn't really a service, but that's my own preference. But I know that this is being renamed due to the change in how the data provider function functions.
> 
> There is an opportunity to have better type validation for the requires arguments to the function which uses the tag. Currently the tests just show `unknown` for the type. The previous version had the linkedProviderId as the first argument. The new form has a request. I think there should be a defined type for that argument type and this type should be required for the function. I would recommend this be done as part of a future change.
> 
> @jeaniehuynh @MiaofeiWang

Thanks @akrantz! Here's [the thread](https://dev.azure.com/office/Office/_git/Office/pullRequest/3418078#1729047962) on how this name was ultimately chosen for some context. "This custom function technically acts as a proxy "service" in the add-in architecture"

Totally agree that it would be nice to have type validation, but the metadata plugin doesn't support Office.js types yet, and the type of `request` is `Excel.Excel.LinkedEntityLoadServiceRequest`. As soon as we have support for this, we will add validation!

**Comment by jeaniehuynh** [comment]
@millerds Seems like there's an unrelated test failure (saw that it failed Miaofei's PR too), is that something you can override to get this checked in?

**Comment by MiaofeiWang** [comment]
> Totally agree that it would be nice to have type validation, but the metadata plugin doesn't support Office.js types yet, and the type of `request` is `Excel.Excel.LinkedEntityLoadServiceRequest`. As soon as we have support for this, we will add validation!

@jeaniehuynh I don't think there is any plan to support all Office.js types in this package. One solution we used before is to treat `Excel.LinkedEntityLoadServiceRequest` as a indeterministic reference type, and we have made such change for `Excel.CellValue`: https://github.com/OfficeDev/Office-Addin-Scripts/blob/ecde2fa315023a0054354f9541adaa07c0253d28/packages/custom-functions-metadata/src/parseTree.ts#L1141 . Here is a test sample: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/custom-functions-metadata/test/cases/input-parameter-types-cellvalue/functions.ts

**Comment by millerds** [comment]
> @millerds Seems like there's an unrelated test failure (saw that it failed Miaofei's PR too), is that something you can override to get this checked in?

This is an incompatibility between the tool and forked repos.  I need to double check on a fix to correct this.  I have been bypassing it for the time being.  Once the comments have been addressed I will do this.

**Comment by jeaniehuynh** [comment]
> > Totally agree that it would be nice to have type validation, but the metadata plugin doesn't support Office.js types yet, and the type of `request` is `Excel.Excel.LinkedEntityLoadServiceRequest`. As soon as we have support for this, we will add validation!
> 
> @jeaniehuynh I don't think there is any plan to support all Office.js types in this package. One solution we used before is to treat `Excel.LinkedEntityLoadServiceRequest` as a indeterministic reference type, and we have made such change for `Excel.CellValue`:
> 
> https://github.com/OfficeDev/Office-Addin-Scripts/blob/ecde2fa315023a0054354f9541adaa07c0253d28/packages/custom-functions-metadata/src/parseTree.ts#L1141
> 
> . Here is a test sample: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/custom-functions-metadata/test/cases/input-parameter-types-cellvalue/functions.ts

Thanks for sharing, @MiaofeiWang! This is a great workaround. @millerds As Adam mentioned, we'll take care of this in a future change as its outside the scope of this change, so we can go ahead and check this one in. Thanks!

**Pull request merged**
