### PR TITLE
office-addin-dev-certs: support Linux

### PR DESCRIPTION
**Pull request by akrantz**
See https://github.com/OfficeDev/Office-Addin-Scripts/pull/199

### CODE REVIEW

**Comment by akrantz** [comment]
There are test failures for Linux in office-addin-debugging related to the port operations done there.

**Comment by ceuk** [comment]
Hi @akrantz had a test fail in `office-addin-debugging` but don't think it's related. Once I commented out the [offending test](https://github.com/akrantz/Office-Addin-Scripts/blob/dev-certs-linux/packages/office-addin-debugging/test/test.ts#L47-L52) everything else looks good.

I'm also able to get all 17 tests to pass locally when running `npm test` directly from the office-addin-dev-certs package directory :+1:

**Comment by akrantz** [comment]
The office-addin-dev-certs tests do pass. They mock things so it was easy to get them to pass. I was also able to manually test the install, verify, and uninstall commands on WSL.

The office-addin-debugging tests with the ports being in use checks are what I want to get working. This works on Mac, but perhaps there is a difference on Linux. I couldn't debug this on WSL. This is what I wanted to figure out so we can actually have this working. It will allow "npm start:web" on linux to start with dev-server to serve up the add-in if not already running.

**Comment by ceuk** [comment]
Ah okay. I just ran the tests on my current machine for office-addin-debugging and they all passed. Looking through the code a bit, it looks like it might be failing on some machines due to [the use of lsof](https://github.com/akrantz/Office-Addin-Scripts/blob/dev-certs-linux/packages/office-addin-debugging/src/port.ts#L53) which isn't installed on some distributions (e.g. arch) and I believe requires sudo on some others. 

Assuming this is indeed the issue - maybe it's worth having a few options depending on what is available? (lsof, netstat, fuser+ls etc)

**Comment by unhammer** [comment]
`fuser -n tcp -4 ${port}` worked on a Centos machine where I had neither lsof nor netstat. 

There's also https://www.npmjs.com/package/tcp-port-used .

**Comment by thatusernamenotavailable** [comment]
Any chance we can get this merged? Or, can I get some pointers on how to install `generator-office` whilst pointed at this branch?

**Comment by TCourtneyOwen** [comment]
@akrantz Is this PR OK to merge? I would like to get a passing CI job run it, but it is otherwise good to go?

**Comment by TCourtneyOwen** [comment]
@thatusernamenotavailable Instructions for using generator-office are located here:  https://github.com/officedev/generator-office

**Comment by igor-ribeiiro** [comment]
Closing this PR as https://github.com/OfficeDev/Office-Addin-Scripts/pull/426 fixed the issue.

**Pull request closed without merging**
